// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFp0bSPMWr_QLIo_voaJqlUUHqk5b56sc',
    appId: '1:1088489193504:web:4f48aa1f1b27c44c893c45',
    messagingSenderId: '1088489193504',
    projectId: 'teste-499a1',
    authDomain: 'teste-499a1.firebaseapp.com',
    storageBucket: 'teste-499a1.appspot.com',
    measurementId: 'G-7EED23W6PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy59iLW6MkM8b5LfQ7g3ylKiGTAqyKsaQ',
    appId: '1:1088489193504:android:c79975362863283f893c45',
    messagingSenderId: '1088489193504',
    projectId: 'teste-499a1',
    storageBucket: 'teste-499a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_uLEi-d8XiKTCmTNKZF5jm_yQOC8X9I',
    appId: '1:1088489193504:ios:126e49c14cea1752893c45',
    messagingSenderId: '1088489193504',
    projectId: 'teste-499a1',
    storageBucket: 'teste-499a1.appspot.com',
    iosBundleId: 'com.example.corteBarbearia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_uLEi-d8XiKTCmTNKZF5jm_yQOC8X9I',
    appId: '1:1088489193504:ios:126e49c14cea1752893c45',
    messagingSenderId: '1088489193504',
    projectId: 'teste-499a1',
    storageBucket: 'teste-499a1.appspot.com',
    iosBundleId: 'com.example.corteBarbearia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFp0bSPMWr_QLIo_voaJqlUUHqk5b56sc',
    appId: '1:1088489193504:web:bac884adff045251893c45',
    messagingSenderId: '1088489193504',
    projectId: 'teste-499a1',
    authDomain: 'teste-499a1.firebaseapp.com',
    storageBucket: 'teste-499a1.appspot.com',
    measurementId: 'G-MZBQ0T0CJ9',
  );
}
